version: '3.9'

services:
  # Frontend EmberJS
  frontend:
    build: ./speech-synthesis-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  # Backend FastAPI
  backend:
    build: ./speech-synthesis-backend
    ports:
      - "8000:8000"
    environment:
      - MISTRAL_API_KEY=xMpsXmyfrawoSqMqryd1re5Ap3ejdBLO
      - DATABASE_URL=postgresql://speech_user:speech_password@db:5432/speech_synthesis_db
    depends_on:
      - db
    volumes:
      - ./speech-synthesis-backend/app:/app/app
    networks:
      - app-network

  # Base de données PostgreSQL
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: speech_synthesis_db
      POSTGRES_USER: speech_user
      POSTGRES_PASSWORD: speech_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./speech-synthesis-backend/app/database/db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge